### ISSUE TITLE
Add Git Cop

### ISSUE THREAD

**Issue by bkuhlmann** [rylanb/boulder-ruby-org#3]
## Overview

Would there be interest in adding [Git Cop](https://github.com/bkuhlmann/git-cop) to this project as a CI linting tool?

By the way, I would highly recommend forcing a rebase workflow. You can enforce this via these [GitHub Settings](https://github.com/bkuhlmann/git-cop#github).

**Comment by rylanb** [comment]
Sure! 

I'll do the rebase setting and see how it goes!

**Comment by bkuhlmann** [comment]
Awesome, this'll be interesting as I've not seen Git Cop run on [Netlify](https://www.netlify.com) before so I wonder if it would require any special configuration.
